const enum IPCChannel {
  /* MainHandlers.ts */
  MINIMISE_WINDOW = "MINIMISE_WINDOW",
  EXPAND_WINDOW = "EXPAND_WINDOW",
  CLOSE_WINDOW = "CLOSE_WINDOW",
  TOGGLE_DEVELOPER_TOOLS = "TOGGLE_DEVELOPER_TOOLS",
  FORCE_RELOAD_WINDOW = "FORCE_RELOAD_WINDOW",

  /* FileHandlers.ts */
  NEW_FILE = "NEW_FILE",
  NEW_FROM_TEMPLATE = "NEW_FROM_TEMPLATE",
  OPEN_FILE = "OPEN_FILE",
  CLOSE_FILE = "CLOSE_FILE",
  SAVE_FILE = "SAVE_FILE",
  GET_FILE_CONTENT = "GET_FILE_CONTENT",
  UPDATE_FILE_CONTENT = "UPDATE_FILE_CONTENT",
  GET_OPENED_FILEPATHS_ASYNC = "GET_OPENED_FILEPATHS_ASYNC",
  RENDERER_UPDATE_OPENED_FILE = "RENDERER_UPDATE_OPENED_FILE",
  GET_FILE_STATE_ASYNC = "GET_FILE_STATE_ASYNC",
  RENDERER_UPDATE_FILE_STATE = "RENDERER_UPDATE_FILE_STATE",
  OPEN_CELLML_DOCUMENTATION = "OPEN_CELLML_DOCUMENTATION",
}

export default IPCChannel;
